In [4]:
import pandas as pd
import numpy as np
import os
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
dp=np.array([[10,5],[2,1],[3,7]])
print(dp)

[[10  5]
 [ 2  1]
 [ 3  7]]


In [3]:
centroids=np.array([[3,4],[6,3],[4,6]])
print(centroids)

[[3 4]
 [6 3]
 [4 6]]


In [5]:
dist=euclidean_distances(dp,centroids)
print(dist)

[[7.07106781 4.47213595 6.08276253]
 [3.16227766 4.47213595 5.38516481]
 [3.         5.         1.41421356]]


In [6]:
np.argmin(dist,axis=1)

array([1, 0, 2], dtype=int64)

In [8]:
from scipy.stats import multivariate_normal

In [9]:
print(multivariate_normal.pdf([10,5],mean=[3,4],cov=[[3,0],[0,3]]))

1.275199678019219e-05


In [10]:
print(multivariate_normal.pdf(dp,mean=[3,4],cov=[[3,0],[0,3]]))

[1.27519968e-05 1.00201619e-02 1.18374226e-02]
